### ISSUE TITLE
Switching from Native to WebView, test hangs and logcat should not be captured when tests in switched to chromedriver

### ISSUE THREAD

**Issue by VinitSandesara** [saikrishna321/AppiumTestDistribution#10]
Hi Sai, After upgrading framework i am seeing an issue in extentReport, PFB screenshot with comment added in. I have added Retry with Test method which is causing below issue, if i remove Retry and run i don't see an issue.

![screen shot 2016-02-07 at 7 40 05 pm](https://cloud.githubusercontent.com/assets/12589206/12877132/df36a44e-cdd3-11e5-9f56-ae51b10f3ef9.png)

![screen shot 2016-02-07 at 7 40 38 pm](https://cloud.githubusercontent.com/assets/12589206/12877133/e3b15cb2-cdd3-11e5-84b4-b1e6fdfedc17.png)

![screen shot 2016-02-07 at 7 40 49 pm](https://cloud.githubusercontent.com/assets/12589206/12877134/e6934f58-cdd3-11e5-9c1b-47f647626d5c.png)

In below list of screenshot you can see extentReport generating as expected but this is without using Retry with Test method. Retry with Test method cause an issue mentioned in above listed screenshot

![screen shot 2016-02-07 at 7 56 40 pm](https://cloud.githubusercontent.com/assets/12589206/12877208/61c98b96-cdd5-11e5-9707-5e980c5a0916.png)

![screen shot 2016-02-07 at 7 56 48 pm](https://cloud.githubusercontent.com/assets/12589206/12877211/68043628-cdd5-11e5-81da-4ff7155bbcf4.png)

![screen shot 2016-02-07 at 7 56 59 pm](https://cloud.githubusercontent.com/assets/12589206/12877212/6a46faba-cdd5-11e5-91bd-5adedbb93c9b.png)

Thanks
Vinit

**Comment by saikrishna321** [comment]
Did u build project locally or using dependency v3.0.4 ?

**Comment by VinitSandesara** [comment]
i build project locally ? i copied "src/main/java" in my project and also your pom.xml. 

Thanks
Vinit

**Comment by jaydeepc** [comment]
@VinitSandesara can you please share a  sample project were ur facing this issue ? I'm unable to reproduce ..

**Comment by saikrishna321** [comment]
@VinitSandesara i have new version, can you  please try with this

https://github.com/saikrishna321/PageObjectPatternAppium/blob/master/pom.xml

https://github.com/saikrishna321/PageObjectPatternAppium/blob/master/src/test/java/com/appium/tests/LoginTest.java#L29

**Comment by VinitSandesara** [comment]
HI Sai, When i try with "https://github.com/saikrishna321/PageObjectPatternAppium.git"  it works fine but lets say if one of the class test gets stuck it mess up the report (in this case it combines the class which test stucked into another class).

Also, when i copy "src/main/java" from "https://github.com/saikrishna321/AppiumTestDistribution.git" in my project i am getting below error msg at the end running using mvn, can you please correct the error so i can continuing using "src/main/java" from yours "https://github.com/saikrishna321/AppiumTestDistribution.git" 


tatus":0,"value":null,"sessionId":"3eadd832-d473-4760-928d-8806c8c11612"}
Feb 08, 2016 2:25:12 PM freemarker.log._JULLoggerFactory$JULLogger error
SEVERE: Error executing FreeMarker template
FreeMarker template error:
The following has evaluated to null or missing:
==> log.stepName  [in template "Extent.ftl" at line 309, column 93]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${log.stepName}  [in template "Extent.ftl" at line 309, column 91]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:131)
	at freemarker.core.EvalUtil.coerceModelToString(EvalUtil.java:355)
	at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:41)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.Environment.process(Environment.java:302)
	at freemarker.template.Template.process(Template.java:325)
	at com.relevantcodes.extentreports.HTMLReporter.flush(HTMLReporter.java:151)
	at com.relevantcodes.extentreports.Report.flush(Report.java:213)
	at com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:491)
	at com.appium.manager.AppiumParallelTest.killAppiumServer(AppiumParallelTest.java:171)
	at apps.sears.config.UserBaseTest.afterClass(UserBaseTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:232)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.appium.executor.MyTestExecutor.testRunnerTestNg(MyTestExecutor.java:101)
	at com.appium.executor.MyTestExecutor$1.run(MyTestExecutor.java:35)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

FreeMarker template error:
The following has evaluated to null or missing:
==> log.stepName  [in template "Extent.ftl" at line 309, column 93]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${log.stepName}  [in template "Extent.ftl" at line 309, column 91]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:131)
	at freemarker.core.EvalUtil.coerceModelToString(EvalUtil.java:355)
	at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:41)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:268)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.Environment.process(Environment.java:302)
	at freemarker.template.Template.process(Template.java:325)
	at com.relevantcodes.extentreports.HTMLReporter.flush(HTMLReporter.java:151)
	at com.relevantcodes.extentreports.Report.flush(Report.java:213)
	at com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:491)
	at com.appium.manager.AppiumParallelTest.killAppiumServer(AppiumParallelTest.java:171)
	at apps.sears.config.UserBaseTest.afterClass(UserBaseTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:232)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.appium.executor.MyTestExecutor.testRunnerTestNg(MyTestExecutor.java:101)
	at com.appium.executor.MyTestExecutor$1.run(MyTestExecutor.java:35)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at java.io.Writer.write(Writer.java:157)
	at com.relevantcodes.extentreports.utils.Writer.write(Writer.java:21)
	at com.relevantcodes.extentreports.HTMLReporter.flush(HTMLReporter.java:164)
	at com.relevantcodes.extentreports.Report.flush(Report.java:213)
	at com.relevantcodes.extentreports.ExtentReports.flush(ExtentReports.java:491)
	at com.appium.manager.AppiumParallelTest.killAppiumServer(AppiumParallelTest.java:171)
	at apps.sears.config.UserBaseTest.afterClass(UserBaseTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:232)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.appium.executor.MyTestExecutor.testRunnerTestNg(MyTestExecutor.java:101)
	at com.appium.executor.MyTestExecutor$1.run(MyTestExecutor.java:35)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Closing Session::3eadd832-d473-4760-928d-8806c8c11612
info: --> POST /wd/hub/session/3eadd832-d473-4760-928d-8806c8c11612/appium/app/close {}
info: JSONWP Proxy: Proxying [DELETE /] to [DELETE http://127.0.0.1:50583/wd/hub/session/e628b9fda98ebf461280342b5c652ff5] with no body
info: JSONWP Proxy: Got response with status 200: {"sessionId":"e628b9fda98ebf461280342b5c652ff5","status":0,"value":null}
info: <-- POST /wd/hub/session/3eadd832-d473-4760-928d-8806c8c11612/appium/app/close 200 808.540 ms - 184 {"status":0,"value":"Successfully closed the [/Users/vsandes/Desktop/searsAndroid_Apps/SearsAndroidApps/build/Sears-debug.apk] app.","sessionId":"3eadd832-d473-4760-928d-8806c8c11612"}

===============================================
Command line suite
Total tests run: 3, Failures: 1, Skips: 1
===============================================

ending
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 128.107 sec - in apps.sears.tests.Runner

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:13 min
[INFO] Finished at: 2016-02-08T14:25:13-06:00
[INFO] Final Memory: 29M/276M
[INFO] ------------------------------------------------------------------------
ushofml916k:SearsAndroidApps vsandes$ 



Thanks
Vinit

**Comment by saikrishna321** [comment]
What you mean by test got stuck ? And can u provide sample  project so that I could reproduce this issue ...

**Comment by VinitSandesara** [comment]
Hi Sai, Please find below sample project i am working on (it's a zip folder). You might need to make some changes in config.properties file. About Test got stuck : i meant to say is that when you 2 class, Runner = distribute, 2 android devices connected, it will distribute both classes on each device, now lets say one of the class (xyz.java) has 2 test method among 1st Test method started executing and at some point that test method got stuck (say element not found and appium session didn't quit) which left there forever in this case it combines this class (xyz.java) with another class (say abc.java) in extentReport.


[SearsAndroidApps.zip](https://github.com/saikrishna321/AppiumTestDistribution/files/122384/SearsAndroidApps.zip)

**Comment by VinitSandesara** [comment]
Hi Sai, Thanks for your quick reply, I have resolved above error by upgrading “com.relevantcodes” jar file from 2.40 to 2.40.1 in pom.xml which has resolved the issue however i am still not getting expected result in extentReport. 

About Test got stuck in my previous msg was : Please find below sample project i am working on, if you run this project thru mvn command on terminal, you will notice LoginTest.java has one of the method which stuck and don’t quit and remains there in this case it combines LoginTest class with SearchTest class in extentReport. You might need to change config.properties configuration 

[SearsAndroidApps.zip](https://github.com/saikrishna321/AppiumTestDistribution/files/122441/SearsAndroidApps.zip)


Thanks
Vinit

**Comment by saikrishna321** [comment]
@VinitSandesara i tried with the sample project and i didn't notice any test hang nor any issues with the report.

<img width="1440" alt="screen shot 2016-02-09 at 9 52 54 pm" src="https://cloud.githubusercontent.com/assets/4045041/12922342/0ba2f416-cf77-11e5-9976-29d49be79b0c.png">

<img width="1440" alt="screen shot 2016-02-09 at 9 53 03 pm" src="https://cloud.githubusercontent.com/assets/4045041/12922348/12d13036-cf77-11e5-9700-3b25711a69ec.png">

**Comment by VinitSandesara** [comment]
Hi Sai, It is still not working, Here i am attaching same project after some modification please find below in which for LoginTest.Java - test method "loginWithInValidUser" - i have added "validateErrorMessage" if you go to that method, you will notice i have intentionally made "Element not found" to replicate an issue. So now if you run this project using mvn on terminal you will see the issue in extentReport like below (LoginTest.java method loginWithInValidUser stuck on device and doesn't move further for 2nd test which produce below extentReport).

![screen shot 2016-02-09 at 3 18 15 pm](https://cloud.githubusercontent.com/assets/12589206/12930879/693c69fe-cf40-11e5-9c7d-eb27d1be283f.png)

![screen shot 2016-02-09 at 3 18 23 pm](https://cloud.githubusercontent.com/assets/12589206/12930882/6e2649bc-cf40-11e5-83ed-89182c6c98b4.png)

![screen shot 2016-02-09 at 3 18 31 pm](https://cloud.githubusercontent.com/assets/12589206/12930887/7185f418-cf40-11e5-83ba-eda76f47dbe0.png)


[SearsAndroidApps.zip](https://github.com/saikrishna321/AppiumTestDistribution/files/123789/SearsAndroidApps.zip)

Thanks
Vinit

**Comment by saikrishna321** [comment]
@VinitSandesara i was able to reproduce the issue. From the appium server logs i see ChromeDriver quitting 

```
Test Failed
Retrying Failed Test Cases 1out of 1
info: --> POST /wd/hub/session/59598262-9d39-47a8-a958-c9e317921baa/appium/app/reset {}
info: JSONWP Proxy: Got response with status 200: {"sessionId":"0074bed09d4033b4154425ed479da546","status":33,"value":{"message":"session not created exception\nfrom unknown error: unhandled inspector error: {\"code\":-32000,\"message\":\"Internal...
info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:50545/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.sears.android","androidUseRunningApp":true,"androidDeviceSerial":"9111833b"}}}
info: JSONWP Proxy: Got response with status 200: {"sessionId":"3d97d0e2df1bf8e4cd1771c8ecfe69e7","status":33,"value":{"message":"session not created exception\nfrom unknown error: unhandled inspector error: {\"code\":-32000,\"message\":\"Internal...
error: Chromedriver: Chromedriver exited unexpectedly with code null, signal SIGTERM
info: Chromedriver: Changed state to 'stopped'
warn: Chromedriver for context WEBVIEW_com.sears.android stopped unexpectedly
warn: Chromedriver quit unexpectedly, but it wasn't the active context, ignoring
error: Chromedriver: Error: A new session could not be created. (Original error: session not created exception
from unknown error: unhandled inspector error: {"code":-32000,"message":"Internal error: main world execution context not found."}
  (Session info: webview=39.0.0.0)
  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Mac OS X 10.10.5 x86_64))
    at JWProxy.command$ (lib/proxy.js:133:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at bound (domain.js:254:14)
    at GeneratorFunctionPrototype.runBound (domain.js:267:12)
    at run (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:17:13)
    at process._tickDomainCallback (node.js:381:11)
 { [Error: A new session could not be created. (Original error: session not created exception
from unknown error: unhandled inspector error: {"code":-32000,"message":"Internal error: main world execution context not found."}
  (Session info: webview=39.0.0.0)
  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Mac OS X 10.10.5 x86_64))]
  status: 33,
  value: { message: 'session not created exception\nfrom unknown error: unhandled inspector error: {"code":-32000,"message":"Internal error: main world execution context not found."}\n  (Session info: webview=39.0.0.0)\n  (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Mac OS X 10.10.5 x86_64)' },
  httpCode: 200 }
info: <-- POST /wd/hub/session/59598262-9d39-47a8-a958-c9e317921baa/appium/app/reset 200 2634.176 ms - 76 {"status":0,"value":null,"sessionId":"59598262-9d39-47a8-a958-c9e317921baa"}
info: --> POST /wd/hub/session/59598262-9d39-47a8-a958-c9e317921baa/log {"type":"logcat"}
info: JSONWP Proxy: Proxying [POST /wd/hub/session/59598262-9d39-47a8-a958-c9e317921baa/log] to [POST http://127.0.0.1:50548/wd/hub/session/450fd08053ee3802f92f6a0b4ac977b3/log] with body: {"type":"logcat"}
info: JSONWP Proxy: Got response with status 200: {"sessionId":"450fd08053ee3802f92f6a0b4ac977b3","status":13,"value":{"message":"unknown error: log type 'logcat' not found\n  (Session info: chrome=47.0.2526.100)\n  (Driver info: chromedriver=2.18...
info: JSONWP Proxy: Replacing sessionId 450fd08053ee3802f92f6a0b4ac977b3 with 59598262-9d39-47a8-a958-c9e317921baa
info: <-- POST /wd/hub/session/59598262-9d39-47a8-a958-c9e317921baa/log 200 3.925 ms - 288

===============================================
Command line suite
Total tests run: 3, Failures: 0, Skips: 3
Configuration Failures: 1, Skips: 4
===============================================

info: Shutting down appium session
info: Shutting down appium session
info: Chromedriver: Changed state to 'stopping'
info: JSONWP Proxy: Proxying [DELETE /] to [DELETE http://127.0.0.1:50548/wd/hub/session/450fd08053ee3802f92f6a0b4ac977b3] with no body
info: JSONWP Proxy: Got response with status 200: "{\"sessionId\":\"450fd08053ee3802f92f6a0b4ac977b3\",\"status\":0,\"value\":null}"
info: Chromedriver: Changed state to 'stopped'
```

And i potentially see a bug as well in the way once we switch to webView, will debug this. 

Can you please try your code without the parallel code just on a single device n see if it works fine?

**Comment by saikrishna321** [comment]
@VinitSandesara would b good if you can come on gitter chat

https://gitter.im/saikrishna321/AppiumTestDistribution?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by VinitSandesara** [comment]
Hi Sai, thank you so much for sharing me gitter chat access. I have joined the group. About this bug how long it will take you fix it and release it ? also as i have mentioned in my last message that after upgrading extentReport dependency in pom.xml from 2.40 to 2.40.1 i am NOT able to run the project from eclipse thru testing.xml, have you also came across this issue ? if i keep 2.40 i am getting ""FreeMarker template error:" so had to upgraded to 2.40.1

Thanks
Vinit

**Comment by saikrishna321** [comment]
@VinitSandesara w.r.t to FreeMarker template its a Bug with Extent reports

https://github.com/anshooarora/extentreports/issues/310
