### ISSUE TITLE
[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for adb. [ADB] Error: Could not find adb Please set the ANDROID_HOME environment variable with the Android SDK root directory path.

### ISSUE THREAD

**Issue by ssrikantasahoo** [saikrishna321/AppiumTestDistribution#109]
Setting Android Desired Capabilities:
Android API Level::19
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/srikantakumarsahoo/Downloads/AndroidCalculator.apk","appPackage":"com.android2.calculator3","appActivity":"com.android2.calculator3.Calculator","platformVersion":"5.X","browserName":"","platformName":"Android","deviceName":"Android"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/srikantakum...
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   app: '/Users/srikantakumarsahoo/Downloads/AndroidCalculator.apk'
[Appium]   appPackage: 'com.android2.calculator3'
[Appium]   appActivity: 'com.android2.calculator3.Calculator'
[Appium]   platformVersion: '5.X'
[Appium]   browserName: ''
[Appium]   platformName: 'Android'
[Appium]   deviceName: 'Android'
[Appium]   udid: 'emulator-5554'
[BaseDriver] Session created with session id: 4f02bce7-02c2-430b-8000-7bba247f4b91
[AndroidDriver] Java version is: 1.8.0_91
[ADB] Checking whether adb is present
[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for adb.
[ADB] Error: Could not find adb Please set the ANDROID_HOME environment variable with the Android SDK root directory path.
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/system-calls.js:85:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Could not find adb Please set the ANDROID_HOME environment variable with the Android SDK root directory path.
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/system-calls.js:85:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'forceStop' of undefined
    at AndroidDriver.deleteSession$ (lib/driver.js:321:19)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by saikrishna321** [comment]
you need to set ANDROID_HOME in your env

**Comment by ssrikantasahoo** [comment]
i have already set ANDROID_HOME

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/issues/3

**Comment by winrad** [comment]
Hi, I am sorry to take your time. I am totally new in Test Automation and I am facing the same problem as you did "ssrikantasahoo". Could you solve the problem? If you did then may you please tell me how you did it? Below is the problem:
[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+.

**Comment by anand853** [comment]
Im hitting the same error now..

**Comment by Anum-Zargar** [comment]
I am getting the same error.Can anyone help me please.Its urgent :-
The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for adb.

**Comment by omoomoniyi** [comment]
I am also experiencing same Issues, I have set ANDROID_HOME to its path but I keep hitting this error message 

"An unknown server-side error occurred while processing the command. Original error: Could not find 'adb.exe' in PATH. Please set the ANDROID_HOME or ANDROID_SDK_ROOT environment variables to the corect Android SDK root directory path."

**Comment by suaadBatis** [comment]
still, this issue displayed with appium 1.16.0

**Comment by fadly-mahendra** [comment]
I got this same error
