### ISSUE TITLE
Cucumber tests do not have the ability to pass desiredCapabilities

### ISSUE THREAD

**Issue by kskrishnan** [saikrishna321/AppiumTestDistribution#119]
Hi @saikrishna321 - I know for testNG tests we can pass the desired caps to startAppiumServerInParallel method. However, this does not work (not available) for ExtentCucumberFormatter > startOfScenarioLifeCycle method. Can we add this?

This aside, the Cucumber tests (both parallel & distributed) seem to be broken now, is it something that would be fixed soon? The below details should help -

In ExtentCucumberFormatter.java, under
public void feature(Feature feature) {
        try {
            **appiumParallelTest.startAppiumServer(feature.getName());**
        } catch (Exception e) {
            e.printStackTrace();
        }
....
...
as you can see from the bold lines (above), the feature name is passed to the startAppiumServer method. This seem to cause the below output (Bottom Navigation menu is the name of my feature)-
{emulator-5554=true}
***************_Device**_*********_**Bottom Navigation Menu_*
_

---

Starting Appium Server to handle Android Device::**Bottom Navigation Menu**

---

This seems to cause the error below as well -
Setting Android Desired Capabilities:
System API Levelnull
java.lang.NumberFormatException: null
    at java.lang.Integer.parseInt(Integer.java:542)
    at java.lang.Integer.parseInt(Integer.java:615)
    at com.appium.manager.AppiumParallelTest.checkSelendroid(AppiumParallelTest.java:300)
    at com.appium.manager.AppiumParallelTest.androidNative(AppiumParallelTest.java:479)
    at com.appium.manager.AppiumParallelTest.startingServerInstance(AppiumParallelTest.java:252)
    at com.appium.manager.AppiumParallelTest.startAppiumServerInParallel(AppiumParallelTest.java:205)
    at com.cucumber.listener.ExtentCucumberFormatter.startOfScenarioLifeCycle(ExtentCucumberFormatter.java:169)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)

Is this something that is known and is there a workaround?

**Comment by saikrishna321** [comment]
@kskrishnan its fixed now 
```
	<dependency>
	    <groupId>com.github.saikrishna321</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version> 5d1ed9602e </version>
	</dependency>
```

**Comment by saikrishna321** [comment]
@kskrishnan merged the PR from @brtu which helps you send caps, please refer the sample 
https://github.com/saikrishna321/AppiumTestDistribution/blob/40f7692eacbc858cffc9923b6208a3541d78a5e1/src/test/java/com/test/cucumber/stepdefinitions/Hooks.java#L21-L22
