### ISSUE TITLE
How to access ExtentReport via MongoDb

### ISSUE THREAD

**Issue by Vishnu1067** [saikrishna321/AppiumTestDistribution#129]
Hello Everyone,

I have installed Mongodb locally and provide the address and port details in config properties. After run the test case How to share the extentreport to everyone with visible screenshots.

When i access http://localhost/27017 it shows 

It looks like you are trying to access MongoDB over HTTP on the native driver port.

Best Regards,
Vish.

**Comment by saikrishna321** [comment]
@Vishnu1067 what is the error your getting or anything is going wrong on reports ?

**Comment by Vishnu1067** [comment]
@saikrishna321 , There were no errors on the execution and report as well. I provided localhost details as 

MONGODB_SERVER=127.0.0.1
MONGODB_PORT=27017

After run the test case, result files can see thro' this address right? http://127.0.0.1/27017

Please correct me if it's wrong.

**Comment by Vishnu1067** [comment]
FYI, I am still using Extent V2 because i can add the screenshots for each test step.

![image](https://cloud.githubusercontent.com/assets/13374564/20162135/8d32b21a-a725-11e6-8415-41bab4c9a1c0.png)

**Comment by saikrishna321** [comment]
No it should be localhost:1337

**Comment by Vishnu1067** [comment]
@saikrishna321 , Have modified the config file and i am facing following issue:

[TestRunner] Starting executor for test TestNG Test with time out:2147483647 milliseconds.
Parallel Thread is::Thread_0
****************Device*************EUYPVK6D6T7S4DSK
Before Class called11
com.test.site.HomePageTest2
After Class11
**************ClosingAppiumSession****************11
FAILED CONFIGURATION: @BeforeClass startAppiumServer("")
java.lang.ExceptionInInitializerError
	at com.appium.manager.AppiumParallelTest.startAppiumServer(AppiumParallelTest.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:1337, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:375)
	at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:104)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71)
	at com.mongodb.binding.ClusterBinding.getReadConnectionSource(ClusterBinding.java:63)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:212)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:483)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:80)
	at com.mongodb.Mongo.execute(Mongo.java:818)
	at com.mongodb.Mongo$2.execute(Mongo.java:805)
	at com.mongodb.FindIterableImpl$FindOperationIterable.first(FindIterableImpl.java:207)
	at com.mongodb.FindIterableImpl.first(FindIterableImpl.java:148)
	at com.aventstack.extentreports.reporter.ExtentXReporter.setupProject(ExtentXReporter.java:198)
	at com.aventstack.extentreports.reporter.ExtentXReporter.start(ExtentXReporter.java:164)
	at com.aventstack.extentreports.Report.attach(Report.java:41)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.aventstack.extentreports.ExtentReports.attachReporter(ExtentReports.java:68)
	at com.report.factory.ExtentManager.getExtent(ExtentManager.java:44)
	at com.report.factory.ExtentTestManager.<clinit>(ExtentTestManager.java:14)
	... 14 more

FAILED CONFIGURATION: @BeforeMethod startApp(public void com.test.site.HomePageTest2.testMethodOne_2() throws java.lang.Exception)
java.lang.NullPointerException
	at com.appium.manager.AppiumParallelTest.setAuthorName(AppiumParallelTest.java:261)
	at com.appium.manager.AppiumParallelTest.startAppiumServerInParallel(AppiumParallelTest.java:229)
	at com.test.site.UserBaseTest.startApp(UserBaseTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:589)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by saikrishna321** [comment]
no don't modify the config, just hit the localhost:1337 in browser .. thats the port sails is running http://extentreports.relevantcodes.com/extentx/

**Comment by Vishnu1067** [comment]
@saikrishna321 Thank you
