### ISSUE TITLE
iOS Web application test run fail

### ISSUE THREAD

**Issue by Vishnu1067** [saikrishna321/AppiumTestDistribution#143]
Hi,

I am trying to execute the test case on iPhone web application but i am facing some challenges. When i choose web, it is directly going to Android driver on start instance

` public void startingServerInstance() throws Exception {
        if (prop.getProperty("APP_TYPE").equalsIgnoreCase("web")) {
            **driver = new AndroidDriver<>(appiumMan.getAppiumUrl(), androidWeb());**
        } else {
            if (System.getProperty("os.name").toLowerCase().contains("mac")) {
                if (iosDevice.checkiOSDevice(device_udid)) {
                    driver = new IOSDriver<>(appiumMan.getAppiumUrl(), iosNative());
                } else if (!iosDevice.checkiOSDevice(device_udid)) {
                    driver = new AndroidDriver<>(appiumMan.getAppiumUrl(), androidNative());
                }
            } else {
                driver = new AndroidDriver<>(appiumMan.getAppiumUrl(), androidNative());
            }
        }
    }`

Does it require to have iOSWeb?

`12-Dec-2016 10:44:042 - Parallel Thread is : 1_f07a0b2df232423feb69fa9160aea4238e124a6c 
/usr/local/lib/node_modules/appium/build/lib
/usr/local/lib/node_modules/appium/bin/ios-webkit-debug-proxy-launcher.js -c f07a0b2df232423feb69fa9160aea4238e124a6c:49537 -d
WebKit Proxy is started on device f07a0b2df232423feb69fa9160aea4238e124a6c and with port number 49537 and in thread 12
Process ID's:{12=1543}
**********************************************************************
Starting Appium Server to handle IOS : f07a0b2df232423feb69fa9160aea4238e124a6c
**********************************************************************
[Appium] Welcome to Appium v1.6.2
[Appium] Non-default server args:
[Appium]   address: '127.0.0.1'
[Appium]   port: 49554
[Appium]   sessionOverride: true
[Appium]   tmpDir: '/Users/vishnu/Vishnu/Framework/automation-framework/rabbitrewards/target/tmp_49554'
[Appium]   webkitDebugProxyPort: 49537
[Appium] Appium REST http interface listener started on 127.0.0.1:49554
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.2","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 15 ms - 83 
12-Dec-2016 10:44:045 - Testcase Name : MTC_ExperiencesRedeemBannerwithLogin 
12-Dec-2016 10:44:045 - ExcelFile - testdata/Rabbit_Rewards.xls 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"browserName":"chrome","udid":"f07a0b2df232423feb69fa9160aea4238e124a6c","platformName":"Android","deviceName":"_","platformVersion":""}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"browserName":"chrome","udid":"f07a0b2df232423feb69fa9160aea4238e124a6c","platformName":"Android","deviceName":"_","platformVersion":""},null,null,null,null]
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   browserName: 'chrome'
[Appium]   udid: 'f07a0b2df232423feb69fa9160aea4238e124a6c'
[Appium]   platformName: 'Android'
[Appium]   deviceName: '_'
[Appium]   platformVersion: ''
[debug] [AndroidDriver] AndroidDriver version: 1.10.36
[BaseDriver] Session created with session id: 49369ae6-455d-45aa-9d1e-f583e73045fd
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_112
[AndroidDriver] We're going to run a Chrome-based session
[AndroidDriver] Chrome-type package and activity are com.android.chrome and com.google.android.apps.chrome.Main
[ADB] Checking whether adb is present
[ADB] Using adb from /usr/local/opt/android-sdk/platform-tools/adb
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active
[MJSONWP] Encountered internal error running command: Error: Could not find a connected Android device.
    at ADB.getDevices$ (../../../lib/tools/system-calls.js:127:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at getDevices (../../../lib/tools/system-calls.js:130:18)
    at ADB.getDevices$ (../../../lib/tools/system-calls.js:144:20)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 22020 ms - 179 
An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 22.13 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'Vishnus-MacBook-Pro.local', ip: '192.168.183.91', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.1', java.version: '1.8.0_112'
Driver info: io.appium.java_client.android.AndroidDriver
[Appium] Received SIGTERM - shutting down
Dec 12, 2016 10:45:13 AM org.openqa.selenium.os.UnixProcess destroy
INFO: Command failed to close cleanly. Destroying forcefully (v2). [/usr/local/bin/node, /usr/local/lib/node_modules/appium/build/lib/main.js, --port, 49554, --address, 127.0.0.1, --log-level, debug, --webkit-debug-proxy-port, 49537, --tmp, /Users/vishnu/Vishnu/Framework/automation-framework/rabbitrewards/target/tmp_49554, --session-override][ {}]

===============================================
Test Suite
Total tests run: 1, Failures: 0, Skips: 1
Configuration Failures: 3, Skips: 0
===============================================

**Comment by saikrishna321** [comment]
@Vishnu1067 i have mentioned in ReadMe that iOS WebTest using Safari is WIP. I haven't got enough time to work on it .. as ios-webkit-proxy is flaky and gets killed we need a place where we should reinitialize it when killed with the same deviceUDID and port. There is a node module which we can use ( monit or pm2 ) which does it .. Would welcome a PR for this

**Comment by Vishnu1067** [comment]
Hi @saikrishna321 ,

I have made changes to launch iOS web Safari,

```public void startingServerInstance(DesiredCapabilities iosCaps, DesiredCapabilities androidCaps) throws Exception {
		// if (prop.getProperty("APP_TYPE").equalsIgnoreCase("web")) {
		// driver = new AndroidDriver<>(appiumMan.getAppiumUrl(),
		// deviceCapabilityManager.androidWeb());
		// } else {
		if (System.getProperty("os.name").toLowerCase().contains("mac")) {
			if (prop.getProperty("IOS_APP_PATH") != null && iosDevice.checkiOSDevice(device_udid)) {
				if (prop.getProperty("APP_TYPE").equalsIgnoreCase("web")) {
					androidCaps = deviceCapabilityManager.iosWeb(device_udid);
				} else if (iosCaps == null) {
					iosCaps = deviceCapabilityManager.iosNative(device_udid);
					if (iosDevice.getIOSDeviceProductVersion(device_udid).contains("10")) {
						iosCaps.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
						iosCaps.setCapability(IOSMobileCapabilityType.WDA_LOCAL_PORT, ports.getPort());
					}
				}
				driver = new IOSDriver<>(appiumMan.getAppiumUrl(), iosCaps);
			} else if (!iosDevice.checkiOSDevice(device_udid)) {
				if (androidCaps == null) {
					androidCaps = deviceCapabilityManager.androidNative(device_udid);
				}
				driver = new AndroidDriver<>(appiumMan.getAppiumUrl(), androidCaps);
			}
		} else {
			if (prop.getProperty("APP_TYPE").equalsIgnoreCase("web")) {
				androidCaps = deviceCapabilityManager.androidWeb();
			} else if (androidCaps == null) {
				androidCaps = deviceCapabilityManager.androidNative(device_udid);
			}
			driver = new AndroidDriver<>(appiumMan.getAppiumUrl(), androidCaps);
		}

	}```

```public synchronized DesiredCapabilities iosWeb(String device_udid) throws InterruptedException, IOException {
		DesiredCapabilities iOSCapabilities = new DesiredCapabilities();
		System.out.println("Setting iOS Desired Capabilities:");
		iOSCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
		iOSCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.0");
		iOSCapabilities.setCapability(MobileCapabilityType.APP, configurationManager.getProperty("IOS_APP_PATH"));
		iOSCapabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Safari");
		iOSCapabilities.setCapability(IOSMobileCapabilityType.AUTO_ACCEPT_ALERTS, true);
		iOSCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone");
		iOSCapabilities.setCapability(MobileCapabilityType.UDID, device_udid);
		return iOSCapabilities;
	}```

I have followed this website **https://discuss.appium.io/t/mobile-web-automation-on-ios-real-device-safari/4900/39** to get installed SafariLauncher. But still safari is not launching and facing some issues.

@here Anyone here successfully running test cases on iOS web?
