### ISSUE TITLE
Cannot run program "flick": error=2, No such file or directory, for iOS devices

### ISSUE THREAD

**Issue by shyam27** [saikrishna321/AppiumTestDistribution#145]
Hi,

Getting below error when tried to record video on iOS devices

**************Starting Video Recording**************
flick video -a start -p ios -u 26d94f19699415d4e66c6bac8ebc059bf9492ed6
java.io.IOException: Cannot run program "flick": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.altimetrik.video.recorder.CommandPrompt.runCommand(CommandPrompt.java:21)
	at com.altimetrik.video.recorder.Flick.flickRecordingCommand(Flick.java:98)
	at com.altimetrik.video.recorder.Flick.startVideoRecording(Flick.java:45)
	at org.openqa.grid.internal.TestSlot.getNewSession(TestSlot.java:123)
	at org.openqa.grid.internal.BaseRemoteProxy.getNewSession(BaseRemoteProxy.java:346)
	at org.openqa.grid.selenium.proxy.DefaultRemoteProxy.getNewSession(DefaultRemoteProxy.java:198)

Thanks,
Shyam.

**Comment by shyam27** [comment]
No Sai, Thanks for the above command to install flick.
