### ISSUE TITLE
Couldnot able run test passing test data using credentials.json file 

### ISSUE THREAD

**Issue by senthilkasiqa** [saikrishna321/AppiumTestDistribution#147]
Hi Sai,
I have been trying to run parallel execution with passing multiple user credentials using credentials.json file, but it is giving me the below error,

FAILED: loginWithValidUser on [MultiLoginTest passed=0 failed=0 skipped=0]
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.appium.config.UserBaseTest.getUserName(UserBaseTest.java:46)
	at com.appium.tests.MultiLoginTest.loginWithValidUser(MultiLoginTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Thanks & Regards,
Senthilkumar K

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/commit/b730151fe1518216de1cf650d4bfa5895f1d04fc
