### ISSUE TITLE
i couldn't able to run the appiumparallel execution using both android and ios capablities.

### ISSUE THREAD

**Issue by senthilkasiqa** [saikrishna321/AppiumTestDistribution#149]
I have used to start startappiumparallel using "driver = startAppiumServerInParallel(name.getName(), iOSCapabilities,androidCap);", in current maven version "fd455e6b1f" to till dwon version " 0ba46c7 " getting error, below this version working fine.
Below the error details,
**************ClosingAppiumSession****************11
FAILED CONFIGURATION: @BeforeMethod startApp(public void com.package.tests.LoginPageTest.verifyLogin())
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.appium.utils.CommandPrompt.runCommandThruProcessBuilder(CommandPrompt.java:47)
	at com.appium.ios.IOSDeviceConfiguration.getIOSDeviceProductVersion(IOSDeviceConfiguration.java:153)
	at com.appium.manager.AppiumParallelTest.iosNative(AppiumParallelTest.java:634)
	at com.appium.config.UserBaseTest.startApp(UserBaseTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:589)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Thanks,
Senthilkumar K

**Comment by RatkoD** [comment]
Can you share the UserBaseTest file?

**Comment by senthilkasiqa** [comment]
Thanks sai!!
It is working fine, i followed your steps.. created separate capabilities for both platforms and passed those capabilities :)
