### ISSUE TITLE
Not able to use test description for the reports

### ISSUE THREAD

**Issue by RatkoD** [saikrishna321/AppiumTestDistribution#161]
In the previous versions I was able to use test description that were shown in the report:
```
@BeforeMethod() public void startApp(Method name) throws Exception {
	Test test = name.getAnnotation(Test.class);
	driver = startAppiumServerInParallel(test.description(), iosNative(), androidNative());
	startLogResults(name.getName());
}
```

Now I get error and I can only use name.getName() which looks bad in the reports.

**Comment by saikrishna321** [comment]
@RatkoD can you please show the previous version screenshot with Description ?

**Comment by RatkoD** [comment]
Here is a [print screen](https://i.imgur.com/mvj8Dcp.png) from extentx report from the previous version where description could be used. If you remember, this was a feature that I proposed a while ago. Reports are much much much better looking with a description instead of long camel sentences.

**Comment by saikrishna321** [comment]
@RatkoD yah i remember, but i dont see any issues in the code. Can tell me what is the error your getting ?

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/manager/AppiumParallelTest.java#L310

**Comment by RatkoD** [comment]
When I use description, I get this error:
```
FAILED CONFIGURATION: @BeforeMethod startApp(public void com.appium.tests.loginTests.QADemo.loginWithValidUserAndSingleProgram() throws java.lang.InterruptedException)
java.lang.NoSuchMethodException: com.appium.tests.loginTests.QADemo.Login with valid credentials and single program()
	at java.lang.Class.getMethod(Class.java:1786)
	at com.appium.manager.AppiumParallelTest.setAuthorName(AppiumParallelTest.java:316)
	at com.appium.manager.AppiumParallelTest.startAppiumServerInParallel(AppiumParallelTest.java:286)
	at com.appium.config.UserBaseTest.startApp(UserBaseTest.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:589)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by saikrishna321** [comment]
@RatkoD try with this version, its fixed.
```
<dependency>
    <groupId>com.github.saikrishna321</groupId>
    <artifactId>AppiumTestDistribution</artifactId>
    <version>a7fe0c9</version>
</dependency>
```

**Comment by RatkoD** [comment]
Now I get this error, no matter if I use description or test name.
```
creating directory: Logs
No Android Device Connected
a55460712308b368e035ad4b61d065460f8966eb

/usr/local/lib/node_modules/appium/build/lib
iOSWebKitProxyLauncher File already has access to execute
a55460712308b368e035ad4b61d065460f8966eb

IOS a55460712308b368e035ad4b61d065460f8966eb Directory is created!
***************************************************

Total Number of devices detected::1

***************************************************

starting running tests in threads
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.061 sec <<< FAILURE! - in com.appium.tests.runners.RunnerQADemo
testApp(com.appium.tests.runners.RunnerQADemo)  Time elapsed: 3.868 sec  <<< FAILURE!
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.appium.executor.MyTestExecutor.constructXmlSuiteForParallel(MyTestExecutor.java:174)
	at com.appium.executor.MyTestExecutor.runMethodParallelAppium(MyTestExecutor.java:128)
	at com.appium.manager.ParallelThread.parallelExecution(ParallelThread.java:142)
	at com.appium.manager.ParallelThread.triggerTest(ParallelThread.java:67)
	at com.appium.manager.ParallelThread.runner(ParallelThread.java:59)
	at com.appium.tests.runners.RunnerQADemo.testApp(RunnerQADemo.java:15)


Results :

Failed tests: 
  RunnerQADemo.testApp:15 » IndexOutOfBounds Index: 0, Size: 0

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.527 s
[INFO] Finished at: 2017-02-03T10:04:09+01:00
[INFO] Final Memory: 24M/309M
```

**Comment by saikrishna321** [comment]
<img width="965" alt="screen shot 2017-02-03 at 5 40 33 pm" src="https://cloud.githubusercontent.com/assets/4045041/22590935/e9ceafba-ea37-11e6-8384-cbc9361496eb.png">

**Comment by saikrishna321** [comment]
@RatkoD can you update the dependency in the sample project and try https://github.com/saikrishna321/PageObjectPatternAppium

**Comment by RatkoD** [comment]
Strange thing, I get the log from above only when I run the tests on iOS, but when I connect Android device it works just fine.

**Comment by saikrishna321** [comment]
@RatkoD can you try with below version, it works for me. Only iOS device connected

```
	<dependency>
	    <groupId>com.github.saikrishna321</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version>c9f7243</version>
	</dependency>
```

**Comment by RatkoD** [comment]
It doesn't work with c9f7243 but it  works just fine c9f7243. I saw that you fixed it.

Thanks Sai!
