### ISSUE TITLE
o.appium.java_client.service.local.InvalidServerInstanceException: Invalid server instance 

### ISSUE THREAD

**Issue by eearif** [saikrishna321/AppiumTestDistribution#183]
after installing the appium with npm install -g appium

when I try to execute the project, it builds fine but when it runs the tests ..
it fails with this exception..

android real device ..

===========

io.appium.java_client.service.local.InvalidServerInstanceException: Invalid server instance exception has occured: The invalid appium node /Users/tthsa1/.nvm/versions/node/v6.7.0/bin/appium/build/lib/main.js has been defined
	at io.appium.java_client.service.local.AppiumServiceBuilder.validateNodeStructure(AppiumServiceBuilder.java:107)
	at io.appium.java_client.service.local.AppiumServiceBuilder.checkAppiumJS(AppiumServiceBuilder.java:290)
	at io.appium.java_client.service.local.AppiumServiceBuilder.createArgs(AppiumServiceBuilder.java:386)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:299)
	at com.appium.manager.AppiumManager.appiumServerForAndroid(AppiumManager.java:62)
	at com.appium.manager.AppiumParallelTest.startAppiumServer(AppiumParallelTest.java:226)
	at com.cucumber.listener.ExtentCucumberFormatter.feature(ExtentCucumberFormatter.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:290)
	at com.sun.proxy.$Proxy14.feature(Unknown Source)
	at cucumber.runtime.junit.JUnitReporter.feature(JUnitReporter.java:165)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:69)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
	at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:62)
	at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:49)
	at com.appium.executor.MyTestExecutor.runTestCase(MyTestExecutor.java:330)
	at com.appium.executor.MyTestExecutor$2.runTests(MyTestExecutor.java:118)
	at com.appium.executor.MyTestExecutor$2.run(MyTestExecutor.java:111)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: The node /Users/tthsa1/.nvm/versions/node/v6.7.0/bin/appium/build/lib/main.jsdoesn't exist
	at io.appium.java_client.service.local.AppiumServiceBuilder.validateNodeStructure(AppiumServiceBuilder.java:109)
	... 43 more

============

Caused by: java.io.IOException: 
The node /Users/tthsa1/.nvm/versions/node/v6.7.0/bin/appium/build/lib/main.js
doesn't exist   at io.appium.java_client.service.local.AppiumServiceBuilder.validateNodeStructure(AppiumServiceBuilder.java:109)
	... 43 more

**Comment by SrinivasanTarget** [comment]
Seems like something to do with your main.js path. Try it out manually ```node <path of your main.js>```.  Update the server logs here in form of gist. You can raise this in discuss forum.

**Comment by saikrishna321** [comment]
closing as java-client side issue
