### ISSUE TITLE
getting java.lang.NullPointerException         at com.cucumber.listener.ExtentCucumberFormatter.step

### ISSUE THREAD

**Issue by hemano** [saikrishna321/AppiumTestDistribution#184]
Referencing : https://github.com/saikrishna321/PageObjectPatternAppium

FAILED: feature(Booking confirmation)
        Runs Cucumber Feature
java.lang.NullPointerException
        at com.cucumber.listener.ExtentCucumberFormatter.step(ExtentCucumberFormatter.java:244)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cucumber.runtime.Utils$1.call(Utils.java:40)
        at cucumber.runtime.Timeout.timeout(Timeout.java:16)
        at cucumber.runtime.Utils.invoke(Utils.java:34)
        at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:294)
        at com.sun.proxy.$Proxy19.step(Unknown Source)
        at cucumber.runtime.model.StepContainer.format(StepContainer.java:33)
        at cucumber.runtime.model.CucumberScenarioOutline.formatOutlineScenario(CucumberScenarioOutline.java:52)
        at cucumber.runtime.model.CucumberScenarioOutline.run(CucumberScenarioOutline.java:41)
        at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
        at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:63)
        at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by benz-philip** [comment]
Trying to run cucumber test by doing prerequisites for cucumber test run, with the same wordpress application test - just for a trial
getting error -- 
![screen shot 2017-05-14 at 6 16 05 pm](https://cloud.githubusercontent.com/assets/18724283/26034713/bf7a0654-38d1-11e7-8ae0-f1df6d361365.png)

please help me resolve this.

**Comment by saikrishna321** [comment]
@benz-philip just gave it a try, can reproduce it.. will fix it soon

**Comment by benz-philip** [comment]
@saikrishna321 : should i attach complete console log if it helps to debug?

**Comment by saikrishna321** [comment]
@benz-philip nope, not needed ....

**Comment by benz-philip** [comment]
Thank you! Is it the issue with the 'AppiumTestDistribution' dependency? Or i can debug it from the test case level?

**Comment by saikrishna321** [comment]
it's at the AppiumTestDistribution library

**Comment by benz-philip** [comment]
Okay Sai, Waiting for a resolution. Thank you

**Comment by saikrishna321** [comment]
@benz-philip can u share your config.properties and also your pom.xml

**Comment by saikrishna321** [comment]
@benz-philip 
can you please try with the below version 


```
<dependency>
            <groupId>com.github.saikrishna321</groupId>
            <artifactId>AppiumTestDistribution</artifactId>
            <version>refactor-2-SNAPSHOT</version>
 </dependency>
```

make sure its testNG in your pom.xml as runner and config.properties

**Comment by benz-philip** [comment]
Sure. Thank you! I will update you once I give it a try.

**Comment by saikrishna321** [comment]
@benz-philip i have fixed this issue for cucumber and tried with PageObjectAppium repo it works fine now.. Give it a try

**Comment by benz-philip** [comment]
I updated the POM with the given dependency version and below is the POM file
![screen shot 2017-05-16 at 2 32 37 pm](https://cloud.githubusercontent.com/assets/18724283/26102169/e95c71f4-3a44-11e7-827d-f74342a7abd0.png)

and below is the config.properties,
![screen shot 2017-05-16 at 2 33 01 pm](https://cloud.githubusercontent.com/assets/18724283/26102180/f62dd364-3a44-11e7-90ba-3031623dbc61.png)

and I get the output with error as,
![screen shot 2017-05-16 at 2 36 18 pm](https://cloud.githubusercontent.com/assets/18724283/26102230/3d031c9a-3a45-11e7-8d80-d16b4d4a747c.png)

**Comment by benz-philip** [comment]
And by keeping 
<useTestNG>true</useTestNG> in pom 
and 
FRAMEWORK=cucumber

Output: 
![cucumber](https://cloud.githubusercontent.com/assets/18724283/26102577/9c2c3818-3a46-11e7-88a6-ed1d32aa485f.png)
Test is not triggering

**Comment by saikrishna321** [comment]
mark your FRAMEWORK as cucumber in properties file

**Comment by benz-philip** [comment]
Thank you, 

And by keeping
useTestNG - true in pom
and
FRAMEWORK=cucumber, ITS WORKING!

RESOLVED!
