### ISSUE TITLE
getSessionDetails().get("platformName") returns Null, causing NullPointerException on test failures.

### ISSUE THREAD

**Issue by 99heitor** [saikrishna321/AppiumTestDistribution#249]
[This line](https://github.com/saikrishna321/AppiumTestDistribution/blob/ae3d207584bd62732ca13eeeee814a489ecd8c4f/src/main/java/com/cucumber/listener/ExtentCucumberFormatter.java#L109) is not currently working on my tests. There's no attribute called "platformName" on the session, which gives me the following error when a scenario fails:
 ```
java.lang.NullPointerException
	at com.cucumber.listener.ExtentCucumberFormatter.result(ExtentCucumberFormatter.java:110)
	at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:290)
	at com.sun.proxy.$Proxy7.result(Unknown Source)
	at cucumber.api.testng.FeatureResultListener.result(FeatureResultListener.java:46)
	at cucumber.runtime.Runtime.runStep(Runtime.java:309)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:63)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Keep in mind I'm on version 7.0.1 so the line numbers might differ from master.

Changing the expression to  
`"Android".equalsIgnoreCase(AppiumDriverManager.getDriver().getSessionDetails().get("platform").toString())` worked fine for me.

Also, I checked my capabilies.json and I am setting the property "platformName" to "android", so that's probably not the problem.

**Comment by saikrishna321** [comment]
Yes, your right. Appium changed the sessionDetails  rendering i have changed it for TestNG not for cucumber. Been a while looked at cucumber runner. PR is welcome on this change :)

**Comment by 99heitor** [comment]
OK, I will open a pull request tomorrow with this change.
