### ISSUE TITLE
Cant launch ios simulator

### ISSUE THREAD

**Issue by ssrikantasahoo** [saikrishna321/AppiumTestDistribution#271]
unning com.appium.tests.Runner
Configuring TestNG with: TestNG652Configurator
java.lang.IllegalArgumentException: No Android Device Connected
	at com.appium.android.AndroidDeviceConfiguration.getDeviceSerial(AndroidDeviceConfiguration.java:105)
	at com.appium.manager.DeviceAllocationManager.getAndroidDeviceSerial(DeviceAllocationManager.java:75)
	at com.appium.manager.DeviceAllocationManager.initializeDevices(DeviceAllocationManager.java:60)
	at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:28)
	at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:33)
	at com.appium.manager.ParallelThread.<init>(ParallelThread.java:47)
	at com.appium.tests.Runner.testRunner(Runner.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:129)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
                            _  _        _ 
 _ __    __ _  _ __   __ _ | || |  ___ | |
| '_ \  / _` || '__| / _` || || | / _ \| |
| |_) || (_| || |   | (_| || || ||  __/| |
| .__/  \__,_||_|    \__,_||_||_| \___||_|
|_|                                       

creating directory: Logs
 _   _          ____                _                     ____                                   _              _ 
| \ | |  ___   |  _ \   ___ __   __(_)  ___   ___  ___   / ___|  ___   _ __   _ __    ___   ___ | |_   ___   __| |
|  \| | / _ \  | | | | / _ \\ \ / /| | / __| / _ \/ __| | |     / _ \ | '_ \ | '_ \  / _ \ / __|| __| / _ \ / _` |
| |\  || (_) | | |_| ||  __/ \ V / | || (__ |  __/\__ \ | |___ | (_) || | | || | | ||  __/| (__ | |_ |  __/| (_| |
|_| \_| \___/  |____/  \___|  \_/  |_| \___| \___||___/  \____| \___/ |_| |_||_| |_| \___| \___| \__| \___| \__,_|
                                                                                                                  

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.550 s
[INFO] Finished at: 2018-01-15T22:36:51+05:30
[INFO] Final Memory: 27M/277M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project PagePatternAppium: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/srikantakumarsahoo/Downloads/workspace/PageObjectPatternAppium && /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/bin/java -jar /Users/srikantakumarsahoo/Downloads/workspace/PageObjectPatternAppium/target/surefire/surefirebooter6740783535798205062.jar /Users/srikantakumarsahoo/Downloads/workspace/PageObjectPatternAppium/target/surefire/surefire6335019669127781187tmp /Users/srikantakumarsahoo/Downloads/workspace/PageObjectPatternAppium/target/surefire/surefire_14722874215102750949tmp
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by saikrishna321** [comment]
@ssrikantasahoo  error cleary says android devices are not connect 

Can you pls tell the command ur using to run and what does adb devices return ?
