### ISSUE TITLE
Respect the key and value as appium does in 1.8.x beta

### ISSUE THREAD

**Issue by saikrishna321** [saikrishna321/AppiumTestDistribution#284]
[BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
[BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
[BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
[BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
[BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
[BaseDriver] Boolean capability passed in as string. Functionality may be compromised.
[XCUITest] InvalidArgumentError: 'wdaLaunchTimeout' must be of type number; 'wdaConnectionTimeout' must be of type number; 'maxTypingFrequency' must be of type number
    at validateCaps (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/capabilities.js:52:11)
    at parseCaps (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/capabilities.js:154:20)
    at processCapabilities (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/capabilities.js:197:43)
    at XCUITestDriver.callee$0$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/session.js:32:14)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)

**Comment by saikrishna321** [comment]
fixed as part of 8.0.0
