### ISSUE TITLE
Appium Server not starting.

### ISSUE THREAD

**Issue by ThamaraiSelvi** [saikrishna321/AppiumTestDistribution#329]
@saikrishna321 I was able to execute the sample project previously, where as now it's prompting me a new exception.

Do I need to change my path of APPIUM_JS_PATH?

Note: I was using the same path previously which was working fine.

**config.properties**
RUNNER=parallel
APPIUM_JS_PATH=C:/Users/thamaraiselvik/AppData/Roaming/npm/node_modules/appium/build/lib/main.js
BROWSER_TYPE=chrome
APP_TYPE=NA
FRAMEWORK=cucumber

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running StepDefinition.RunnerCukes
Configuring TestNG with: TestNG652Configurator
OUTPUT DIRECTORY :D:\Android\ParallelSulekha\target
                            _  _        _
 _ __    __ _  _ __   __ _ | || |  ___ | |
| '_ \  / _` || '__| / _` || || | / _ \| |
| |_) || (_| || |   | (_| || || ||  __/| |
| .__/  \__,_||_|    \__,_||_||_| \___||_|
|_|

***************************************************

Total Number of devices detected::2

***************************************************

starting running tests in threads
creating directory: Logs
May 17, 2018 3:50:15 PM com.appium.manager.DeviceAllocationManager getDevices
INFO: All devices connected
creating directory: ADBLogs
...
... TestNG 6.11 by CΘdric Beust (cedric@beust.com)
...

**************************************************************************

Starting Appium Server on Localhost......
**************************************************************************

Picking Default Path for AppiumServiceBuilder
io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyExceptio
n: The local appium server has not been started. The given Node.js executable: C
:\Program Files\nodejs\node.exe Arguments: [C:\Users\thamaraiselvik\AppData\Roam
ing\npm\node_modules\appium\build\lib\main.js, --port, 36665, --address, 127.0.0
.1, --log, D:\Android\ParallelSulekha\target\appiumlogs\appium_logs.txt, --log-l
evel, info]

        at io.appium.java_client.service.local.AppiumDriverLocalService.start(Ap
piumDriverLocalService.java:155)
        at com.appium.manager.LocalAppiumManager.startAppiumServer(LocalAppiumMa
nager.java:75)
        at com.appium.manager.AppiumServerManager.startAppiumServerSingleSession
(AppiumServerManager.java:35)
        at com.appium.manager.AppiumServerManager.startAppiumServer(AppiumServer
Manager.java:53)
        at com.cucumber.listener.ExtentCucumberFormatter.onStart(ExtentCucumberF
ormatter.java:363)
        at org.testng.SuiteRunner.invokeListeners(SuiteRunner.java:226)
        at org.testng.SuiteRunner.run(SuiteRunner.java:287)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
        at org.testng.TestNG.runSuites(TestNG.java:1144)
        at org.testng.TestNG.run(TestNG.java:1115)
        at com.appium.executor.MyTestExecutor.runMethodParallel(MyTestExecutor.j
ava:174)
        at com.appium.manager.ParallelThread.parallelExecution(ParallelThread.ja
va:155)
        at com.appium.manager.ParallelThread.triggerTest(ParallelThread.java:90)

        at com.appium.manager.ParallelThread.runner(ParallelThread.java:82)
        at com.appium.manager.ParallelThread.runner(ParallelThread.java:86)
        at StepDefinition.RunnerCukes.testCukesRunner(RunnerCukes.java:12)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(Framework
Method.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCal
lable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMe
thod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMet
hod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
ner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
ner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
        at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:82)
        at org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:70)
        at org.testng.TestRunner$1.run(TestRunner.java:667)
        at org.testng.TestRunner.runJUnitWorkers(TestRunner.java:950)
        at org.testng.TestRunner.privateRunJUnit(TestRunner.java:698)
        at org.testng.TestRunner.run(TestRunner.java:599)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
        at org.testng.SuiteRunner.run(SuiteRunner.java:289)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
        at org.testng.TestNG.runSuites(TestNG.java:1144)
        at org.testng.TestNG.run(TestNG.java:1115)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.ja
va:115)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSing
leClass(TestNGDirectoryTestSuite.java:129)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(Tes
tNGDirectoryTestSuite.java:113)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider
.java:111)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameCla
ssLoader(ForkedBooter.java:203)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(Fork
edBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:
103)
Caused by: java.lang.IllegalAccessError: tried to access method com.google.commo
n.util.concurrent.SimpleTimeLimiter.<init>(Ljava/util/concurrent/ExecutorService
;)V from class org.openqa.selenium.net.UrlChecker
        at org.openqa.selenium.net.UrlChecker.<init>(UrlChecker.java:67)
        at io.appium.java_client.service.local.AppiumDriverLocalService.ping(App
iumDriverLocalService.java:115)
        at io.appium.java_client.service.local.AppiumDriverLocalService.start(Ap
piumDriverLocalService.java:142)
        ... 60 more

===============================================
    TestNG Test0
    Tests run: 0, Failures: 0, Skips: 0
===============================================

===============================================
    TestNG Test1
    Tests run: 0, Failures: 0, Skips: 0
===============================================

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 33.771 sec <<< F
AILURE! - in StepDefinition.RunnerCukes
testCukesRunner on testCukesRunner(StepDefinition.RunnerCukes)(StepDefinition.Ru
nnerCukes)  Time elapsed: 32.778 sec  <<< FAILURE!
java.lang.NullPointerException: null
        at com.appium.manager.LocalAppiumManager.destroyAppiumNode(LocalAppiumMa
nager.java:45)
        at com.appium.manager.AppiumServerManager.stopAppiumServer(AppiumServerM
anager.java:60)
        at com.cucumber.listener.ExtentCucumberFormatter.onFinish(ExtentCucumber
Formatter.java:372)
        at org.testng.SuiteRunner.invokeListeners(SuiteRunner.java:229)
        at org.testng.SuiteRunner.run(SuiteRunner.java:292)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
        at org.testng.TestNG.runSuites(TestNG.java:1144)
        at org.testng.TestNG.run(TestNG.java:1115)
        at com.appium.executor.MyTestExecutor.runMethodParallel(MyTestExecutor.j
ava:174)
        at com.appium.manager.ParallelThread.parallelExecution(ParallelThread.ja
va:155)
        at com.appium.manager.ParallelThread.triggerTest(ParallelThread.java:90)

        at com.appium.manager.ParallelThread.runner(ParallelThread.java:82)
        at com.appium.manager.ParallelThread.runner(ParallelThread.java:86)
        at StepDefinition.RunnerCukes.testCukesRunner(RunnerCukes.java:12)

Results :

Failed tests:
  RunnerCukes.testCukesRunner:12 ╗ NullPointer

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:01 min
[INFO] Finished at: 2018-05-17T15:50:47+05:30
[INFO] Final Memory: 26M/214M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
18.1:test (default-test) on project ParallelSulekha: There are test failures.
[ERROR]
[ERROR] Please refer to D:\Android\ParallelSulekha\target\surefire-reports for t
he individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

**Comment by saikrishna321** [comment]
>D:\Android\ParallelSulekha\target\appiumlogs\appium_logs.txt

Whats in this log? Error is from java-client

**Comment by ThamaraiSelvi** [comment]
@saikrishna321 Appium logs are not generated.
![image](https://user-images.githubusercontent.com/5635111/40217527-ed77441e-5a8a-11e8-8967-92eec37ed111.png)

**Comment by saikrishna321** [comment]
C:\Users\thamaraiselvik\AppData\Roam
ing\npm\node_modules\appium\build\lib\main.js running this from commandline, works?

**Comment by ThamaraiSelvi** [comment]
@saikrishna321 
![image](https://user-images.githubusercontent.com/5635111/40218141-95b33a32-5a8d-11e8-9b5f-b4ebea427c49.png)
