### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by SNaishta** [saikrishna321/AppiumTestDistribution#343]
Hello,

Can you please help , I am getting the below error

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.appium.tests.Runner
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
	at org.json.JSONObject.<init>(JSONObject.java:214)
	at org.json.JSONObject.<init>(JSONObject.java:357)
	at com.appium.utils.JsonParser.getObjectFromJSON(JsonParser.java:38)
	at com.appium.utils.CapabilityManager.<init>(CapabilityManager.java:21)
	at com.appium.utils.CapabilityManager.getInstance(CapabilityManager.java:26)
	at com.appium.utils.HostMachineDeviceManager.<init>(HostMachineDeviceManager.java:29)
	at com.appium.utils.HostMachineDeviceManager.getInstance(HostMachineDeviceManager.java:38)
	at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:37)
	at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:52)
	at com.appium.manager.ParallelThread.<init>(ParallelThread.java:54)
	at com.appium.tests.Runner.testRunner(Runner.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.399 sec <<< FAILURE! - in com.appium.tests.Runner
testRunner(com.appium.tests.Runner)  Time elapsed: 0.038 sec  <<< FAILURE!
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at com.appium.tests.Runner.testRunner(Runner.java:13)

Results :

Failed tests: 
  Runner.testRunner:13 » JSON A JSONObject text must begin with '{' at 1 [charac...

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

**Comment by saikrishna321** [comment]
@SNaishta can you please refer https://github.com/saikrishna321/PageObjectPatternAppium/blob/master/caps/capabilities.json

**Comment by SNaishta** [comment]
Many Thanks , Issue is resolved
