### ISSUE TITLE
Unable to run the test from maven command line

### ISSUE THREAD

**Issue by spartanglady** [saikrishna321/AppiumTestDistribution#367]
When I try to run the test as a suite from command line 

Platform="android" mvn clean -Dtest Runner test

I'm getting the below error right after the app is lauched

**[HTTP] <-- GET /wd/hub/session/d52ad882-b95b-4f43-81bf-71fe79d608a9 200 3 ms - 1109 
[HTTP] --> POST /wd/hub/session/d52ad882-b95b-4f43-81bf-71fe79d608a9/log {"type":"logcat"}
[debug] [MJSONWP] Calling AppiumDriver.getLog() with args: ["logcat","d52ad882-b95b-4f43-81bf-71fe79d608a9"]
[debug] [MJSONWP] Responding to client with driver.getLog() result: [{"timestamp":1532559496173,"level":"ALL","message":"--------- beginning of crash"},{"timestamp":1532559496173,"level":"ALL","message":"07-24 09:49:45.041 17908 17936 E AndroidRuntime: FATAL EXCEPTION: Instr: android.support.test.runner.AndroidJUnitRunner"},{"timestamp":1532559496173,"level":"ALL","message":"07-24 09:49:45.041 17908 17936 E AndroidRuntime: Process: io.appium.uiautomator2.server, PID: 17908"},{"timestamp":1532559496173,"level":"ALL","message":"07-24 09:49:45.041 17908 17936 E AndroidRuntime: java.lang.IllegalStateException: UiAutomation not connected!"},{"timestamp":1532559496173,"level":"ALL","message":"07-24 09:49:45.041 17908 17936 E AndroidRuntime: \tat android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1096)"},{"timestamp":1532559496173,"level":"ALL","message":"07-24 09:49:45.041 17908 17936 E AndroidRuntime: \tat android.app.UiAutomation.disconnect(UiAutomation.java:275)"},{"timestamp":1532559496173,"level":"ALL","message":"07-24 09:49:45.041 17908 17936 E AndroidRun...
[HTTP] <-- POST /wd/hub/session/d52ad882-b95b-4f43-81bf-71fe79d608a9/log 200 34 ms - 1182165 
LoginDDAWithoutRisk execution failed in count: 0
**

But if run the same test by manually starting the Appium server as individual tests, it's working fine.

**Here is the stack trace**
java.lang.IllegalArgumentException: unexpected url: http://null:null/testresults
        at okhttp3.Request$Builder.url(Request.java:143)
        at com.appium.utils.Api.post(Api.java:52)
        at com.appium.utils.Helpers.sendResultsToAtdService(Helpers.java:48)
        at com.appium.manager.AppiumParallelTestListener.beforeInvocation(AppiumParallelTestListener.java:58)
        at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeBeforeInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:84)
        at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
        at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:566)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:644)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.privateRun(TestRunner.java:744)
        at org.testng.TestRunner.run(TestRunner.java:602)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
        at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
        at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
        at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by saikrishna321** [comment]
can u pls share the dependency version ur using ?

**Comment by spartanglady** [comment]
I believe its the problem in a specific version. I got it working on this version c511401d4392a485ee1fe2339ab0abf58c90aefb. But this 088478e376 is not working. If I'm pointing to the wrong one, can you tell the latest working version.

**Comment by saikrishna321** [comment]
can u pls post your capabilities.json

**Comment by spartanglady** [comment]
{
  "android": {
    "platformName": "android",
    "platformVersion": "8.0",
    "app": "./build/abc.apk",
    "appWaitActivity": "com.xyz.abc",
    "deviceName": "android",
    "noSign": true
  },
  "iOS": {
    "platformName": "iOS",
    "app": {
      "simulator": "./build/abc.app"
    },
    "deviceName": "iPhone",
    "usePrebuiltWDA": true,
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": true,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "maxTypingFrequency": 10
  },
  "hostMachines": [
    {
      "machineIP": "127.0.0.1",
      "simulators": [
        {
          "deviceName": "iPhone X",
          "OS": "11.4"
        }
      ]
    }
  ]
}

**Comment by saikrishna321** [comment]
@spartanglady can you try with below version 

```
	<dependency>
	    <groupId>com.github.saikrishna321</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version>ef39d1cdd0</version>
	</dependency>
```

**Comment by spartanglady** [comment]
This version is not working for me. Same error 
java.lang.IllegalArgumentException: unexpected url: http://null:null/testresults

**Comment by saikrishna321** [comment]
@spartanglady will fix this today. Thanks for reporting. Meantime you can just add this to your capabilties.json

```
"ATDServiceHost":"127.0.0.1",
"ATDServicePort":"3000"
```

**Comment by SrinivasanTarget** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/commit/b7aa268ba8f7a002c90e1d2a5bbbea8d83dbd757

**Comment by spartanglady** [comment]
Thanks.
