### ISSUE TITLE
Run the PageObjectPatternAppium demo issue

### ISSUE THREAD

**Issue by qileilove** [saikrishna321/AppiumTestDistribution#55]
hi saikrishna, when i use the demo for PatternAppium, i get some issue,i don't know why. can you give me some help on it? 

```
T E S T S
-------------------------------------------------------
Running com.appium.tests.Runner
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@2a098129
creating directory: Logs
creating directory: ADBLogs
Android 192.168.99.102:5555 Directory is created!
Android 192.168.99.101:5555 Directory is created!
java.io.IOException: Cannot run program "idevice_id": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.appium.utils.CommandPrompt.runCommand(CommandPrompt.java:21)
	at com.appium.ios.IOSDeviceConfiguration.getIOSUDID(IOSDeviceConfiguration.java:37)
	at com.appium.manager.ParallelThread.runner(ParallelThread.java:61)
	at com.appium.tests.Runner.testRunner(Runner.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 40 more
Total Number of devices detected::2
```

**Comment by qileilove** [comment]
ok, it works now. I used the wrong configuration file.  but still have same issue,but don't affect use. i don't konw why it happened.

**Comment by saikrishna321** [comment]
@qileilove r u running your test on windows / mac ?

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/AppiumTestDistribution/issues/50

**Comment by qileilove** [comment]
@saikrishna321 i running the test on mac and os x with Appium version 1.5.1

**Comment by saikrishna321** [comment]
@qileilove https://github.com/saikrishna321/AppiumTestDistribution/wiki/Prerequisites#ios-real-device

if your running your tests over mac, the FW looks if iOS devices are connected as well. If yes it will pick iOS devices and android devices and run the tests in parallel . 

brew install libimobiledevice libplist libtasn1 usbmuxd openssl ideviceinstaller

**Comment by qileilove** [comment]
thanks @saikrishna321

**Comment by saikrishna321** [comment]
@qileilove did that help u run the tests ?
