### ISSUE TITLE
Execution is blocked due to java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by YagneshShah** [saikrishna321/AppiumTestDistribution#74]
In Windows 8,
For the first time execution the "extent.xml" file doesn't exist, then following warning is encountered and execution is stopped. 

Jun 15, 2016 5:40:58 PM com.relevantcodes.extentreports.ExtentReports loadConfig
WARNING: Unable to perform report configuration. The file C:\Users\Qapitol QA\IdeaProjects\flipkartSampleWithoutPageObjectMaven\extent.xml was not found.

java.lang.NumberFormatException: For input string: ""

	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	
Screenshot: http://screencast.com/t/umFG3eIX3O

Solution suggested: 
case 1:
--------
Give control to user to turn for extent report to enable/disable via config.properties file

case 2:
--------
Can we get the fix for:
java.lang.NumberFormatException: For input string: ""

	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)

This issue is noted when multiple devices are connected.

**Comment by saikrishna321** [comment]
@YagneshShah from your screenshot i see your udid is 12345678ABCDE- which i feel is not your real device UDID serial, how r u sending this ?

**Comment by saikrishna321** [comment]
can you give the server logs pls

**Comment by YagneshShah** [comment]
2016-06-20 09:15:05:829 - info: [Appium] Welcome to Appium v1.5.2
2016-06-20 09:15:05:838 - info: [Appium] Non-default server args:
2016-06-20 09:15:05:844 - info: [Appium]   port: 59322
2016-06-20 09:15:05:845 - info: [Appium]   bootstrapPort: 59324
2016-06-20 09:15:05:846 - info: [Appium]   sessionOverride: true
2016-06-20 09:15:05:849 - info: [Appium]   log: 'C:\\Users\\Qapitol QA\\IdeaProjects\\flipkartSampleWithoutPageObjectMaven\\target\\appiumlogs\\0123456789ABCDEF__validLoginTest.txt'
2016-06-20 09:15:05:851 - info: [Appium]   loglevel: 'info'
2016-06-20 09:15:05:852 - info: [Appium]   selendroidPort: 59325
2016-06-20 09:15:05:853 - info: [Appium]   chromeDriverPort: 59323
2016-06-20 09:15:05:855 - info: [Appium]   suppressAdbKillServer: true
2016-06-20 09:15:05:859 - info: [Appium]   udid: '0123456789ABCDEF'
2016-06-20 09:15:05:868 - warn: [Appium] Deprecated server args:
2016-06-20 09:15:05:870 - warn: [Appium]   -U,--udid => --default-capabilities '{"udid":"0123456789ABCDEF"}'
2016-06-20 09:15:05:872 - info: [Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
2016-06-20 09:15:05:953 - info: [Appium]   udid: '0123456789ABCDEF'
2016-06-20 09:15:06:407 - info: [Appium] Appium REST http interface listener started on 0.0.0.0:59322
2016-06-20 09:15:06:822 - info: [HTTP] --> GET /wd/hub/status {}
2016-06-20 09:15:06:833 - info: [MJSONWP] Calling AppiumDriver.getStatus() with args: []
2016-06-20 09:15:06:870 - info: [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.2","revision":null}}
2016-06-20 09:15:06:903 - info: [HTTP] <-- GET /wd/hub/status 200 61 ms - 83

**Comment by saikrishna321** [comment]
Can u post adb devices what it shows ?

**Comment by saikrishna321** [comment]
Closing this issue as the two devices got  the same UDID
