### ISSUE TITLE
InvalidNodeJSInstance  exception while launching the Appium server 

### ISSUE THREAD

**Issue by raveendaranugu** [saikrishna321/AppiumTestDistribution#77]
Hi @saikrishna321.
While executing the script I am getting following exception though Node.js is already installed on my machine and path was set to Environment variables.

Below are the exception details.

**io.appium.java_client.service.local.InvalidNodeJSInstance: Node.js is not installed!
    at io.appium.java_client.service.local.AppiumServiceBuilder.findDefaultExecutable(AppiumServiceBuilder.java:201)
    at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:296)
    at com.appium.manager.AppiumManager.appiumServerForAndroid(AppiumManager.java:60)
    at com.appium.manager.AppiumParallelTest.startAppiumServer(AppiumParallelTest.java:156)
    at com.test.site.UserBaseTest.beforeClass(UserBaseTest.java:43)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
    at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
    at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
    at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
    at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Unable to find executable for: node.exe**
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:251)
    at org.openqa.selenium.os.UnixProcess.<init>(UnixProcess.java:62)
    at org.openqa.selenium.os.CommandLine.<init>(CommandLine.java:38)
    at io.appium.java_client.service.local.AppiumServiceBuilder.findDefaultExecutable(AppiumServiceBuilder.java:195)
    ... 17 more

SKIPPED CONFIGURATION: @BeforeMethod startApp
SKIPPED CONFIGURATION: @AfterMethod killServer
SKIPPED CONFIGURATION: @BeforeMethod startApp
SKIPPED CONFIGURATION: @AfterMethod killServer
SKIPPED CONFIGURATION: @BeforeMethod startApp
SKIPPED CONFIGURATION: @AfterMethod killServer
SKIPPED CONFIGURATION: @BeforeMethod startApp
SKIPPED CONFIGURATION: @AfterMethod killServer
SKIPPED CONFIGURATION: @AfterClass afterClass
FAILED: testMethodOne_1 on [HomePageTest1 passed=0 failed=0 skipped=0]
java.lang.NullPointerException
    at com.appium.manager.AppiumParallelTest.onTestStart(AppiumParallelTest.java:500)
    at org.testng.internal.Invoker.runTestListeners(Invoker.java:1904)
    at org.testng.internal.Invoker.runTestListeners(Invoker.java:1879)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:685)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

FAILED: testMethodOne_1 on [HomePageTest1 passed=0 failed=0 skipped=0]
java.lang.NullPointerException
    at com.appium.manager.AppiumParallelTest.onTestStart(AppiumParallelTest.java:500)
    at org.testng.internal.Invoker.runTestListeners(Invoker.java:1904)
    at org.testng.internal.Invoker.runTestListeners(Invoker.java:1879)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:685)
    at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by saikrishna321** [comment]
@raveendaranugu if your running the tests from eclipse then u need to set PATH and ANDROID_HOME 

https://cloud.githubusercontent.com/assets/12589206/12456474/a0040590-bf65-11e5-9528-d246cbee4f15.png

**Comment by raveendaranugu** [comment]
Thank you @saikrishna321 .
For time being I am executing the script thru command prompt. It's working fine but when I execute it for second time the .apk file is getting deleted from its location.Below is the appium logs.

**2016-06-28 13:34:57:413 - warn: UiAutomator did not shut down fast enough, calling it gone
2016-06-28 13:34:57:420 - error: Failed to start an Appium session, err was: Error: Command failed: C:\windows\system32\cmd.exe /s /c "java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\sign.jar" "D:\CeX Beta.apk" --override"
java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:145)
	at s.Sign.sign(Sign.java:441)
	at s.Sign.main(Sign.java:532)

2016-06-28 13:34:57:432 - info: <-- POST /wd/hub/session 500 17510.572 ms - 1529**

**Comment by raveendaranugu** [comment]
@saikrishna321 

Connected 3 Android devices to the machine. But able to execute on only 2 devices.On 3rd devices it is giving the below error .
**error: Failed to start an Appium session, err was: Error: EPERM: operation not permitted, rename 'C:\Users\RAVIND~1\AppData\Local\Temp\116528-6744-js843f\appium.tmp' ->**

The 3rd device is Rooted device. is this the reason for getting the above error?

**Comment by saikrishna321** [comment]
@raveendaranugu no this is issue is something to do with your system permission

**Comment by raveendaranugu** [comment]
I am running the script as Administrator .There is no issue with other 2 devices.but why this kind of issue is  with only 1 device. 
@saikrishna321  And I have a doubt that what is the difference between **"RUNNER=distribute and RUNNER=parallel"**   ?Could you please clarify this?

**Comment by saikrishna321** [comment]
Distribute -- 3 test cases and 3 devices each test case will go to each device ... TC1 -- Device 1, TC2 -- Device 2, TC3 -- Device 3 

Parallel -- TC1,TC2,TC3 will go device1,device2,device3 which will give u device coverage
