### ISSUE TITLE
Sending the desiredCapabiliteis makes the framework platform dependant

### ISSUE THREAD

**Issue by RatkoD** [saikrishna321/AppiumTestDistribution#84]
I've started using the new feature, to send desiredCapabilities to the tests but there is a problem. Here is how it goes:

If I set 
```
	@BeforeMethod() public void startApp(Method name) throws Exception {
		Test test = name.getAnnotation(Test.class);
		driver = startAppiumServerInParallel(test.description(), androidNative());
		startLogResults(name.getName());
	}
```
and connect only Android devices it works. If I connect iOS devices it fails with 

```
Starting Appium Server to handle IOS::c205d576285a38492cce0f8580c007f0abf37fac

**********************************************************************

[Appium] Welcome to Appium v1.5.3 (REV 2cd81e50513f96a657454031e52fa4aec773ea97)
[Appium] Non-default server args:
[Appium]   port: 59617
[Appium]   sessionOverride: true
[Appium]   log: '/Users/ratkododevski/Documents/workspace/HRHeroQA/target/appiumlogs/c205d576285a38492cce0f8580c007f0abf37fac__LoginTest.txt'
[Appium]   tmpDir: '/Users/petko/Documents/workspace/HRHeroQA/target/tmp_59617'
[Appium]   webkitDebugProxyPort: 59476
[Appium] Appium REST http interface listener started on 0.0.0.0:59617
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 16 ms - 121 
Setting Android Desired Capabilities:

java.lang.NumberFormatException: For input string: ""
```

If I connect mix of android and ios devices, it runs only on android devices.

If I set 
```
	@BeforeMethod() public void startApp(Method name) throws Exception {
		Test test = name.getAnnotation(Test.class);
		driver = startAppiumServerInParallel(test.description(), iosNative());
		startLogResults(name.getName());
	}
```
and connect only iOS devices it works. If I connect Android devices it fails with:

```
**************************************************************************

Starting Appium Server to handle Android Device::0085f5078a7d484b

**************************************************************************

[Appium] Welcome to Appium v1.5.3 (REV 2cd81e50513f96a657454031e52fa4aec773ea97)
[Appium] Non-default server args:
[Appium]   port: 65249
[Appium]   bootstrapPort: 65251
[Appium]   sessionOverride: true
[Appium]   log: '/Users/ratkododevski/Documents/workspace/HRHeroQA/target/appiumlogs/0085f5078a7d484b__LoginTest.txt'
[Appium]   loglevel: 'info'
[Appium]   selendroidPort: 65252
[Appium]   chromeDriverPort: 65250
[Appium]   suppressAdbKillServer: true
[Appium] Appium REST http interface listener started on 0.0.0.0:65249
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 15 ms - 121 
Setting iOS Desired Capabilities:
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"https://mobile-ci.rg.co/job/mob-03-ios-build/206/artifact/build/package/mob-03-Appium.ipa","bundleId":"com.rewardgateway.mob-03","udid":"0085f5078a7d484b","platformName":"iOS","deviceName":"iPhone","autoAcceptAlerts":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"https://mobile-ci....
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   app: 'https://mobile-ci.rg.co/job/mob-03-ios-build/206/artifact/build/package/mob-03-Appium.ipa'
[Appium]   bundleId: 'com.rewardgateway.mob-03'
[Appium]   udid: '0085f5078a7d484b'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone'
[Appium]   autoAcceptAlerts: true
[BaseDriver] Session created with session id: 02391e31-a9b8-43da-ad5c-3a5de180aaeb
[BaseDriver] Using downloadable app 'https://mobile-ci.rg.co/job/mob-03-ios-build/206/artifact/build/package/mob-03-Appium.ipa'
[BaseDriver] Downloaded app to '/var/folders/pp/123fdrgn31d40yvyxxkb6sf00000gp/T/201668-14460-1aaeupk/appium-app.zip'
[BaseDriver] Unzipped local app to '/var/folders/pp/123fdrgn31d40yvyxxkb6sf00000gp/T/201668-14460-1aaeupk/Payload/mob-03.app'
[iOS] Could not file localizable strings file 'Localizable.strings'!
[MJSONWP] Encountered internal error running command: Error: Command failed: /bin/sh -c ideviceinstaller -u 0085f5078a7d484b -l 

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
[HTTP] <-- POST /wd/hub/session 500 10705 ms - 206 

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Command failed: /bin/sh -c ideviceinstaller -u 0085f5078a7d484b -l 
 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10.88 seconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'RatkoD.local', ip: '10.69.69.233', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_73'
Driver info: io.appium.java_client.ios.IOSDriver
```

If I connect mix of android and iOS devices, it runs only on the iOS devices.

This way, the code is platform dependant and can run only one type of devices, instead of running on android and iOS in parallel.

Tried with removing synchronized from the androidNative() as suggested, but it works the same.

**Comment by saikrishna321** [comment]
@SrinivasanTarget check this bro

**Comment by SrinivasanTarget** [comment]
👍
