### ISSUE TITLE
Scripts are not executing Parallely on Android

### ISSUE THREAD

**Issue by dkjha52** [saikrishna321/AppiumTestDistribution#87]
Hi Sai,

I executed the sample scripts but scripts are not executing parallely on android devices. Scripts are executing only on single devices. However I have connected 2 android devices. Please let me know if there is any other steps which I need to follow.

-Dhirendra

**Comment by RatkoD** [comment]
Hey @dkjha52, can you list the devices using adb devices command? Are you running the tests from command line or from Eclipse/IntelliJ etc? If you run the tests from editor, only one device will  be used, but if you run the tests from cli it will run the tests in distribute/parallel.

**Comment by dkjha52** [comment]
I am running the test from Eclipse and shows the correct number of devices. Now this issue has been resolved and working fine. After that getting different issue. After completed the test, shows below exception - 
FAILED: testRunner
java.lang.NullPointerException
	at com.appium.utils.ImageUtils.creatResultsSet(ImageUtils.java:63)
	at com.appium.executor.MyTestExecutor.runMethodParallelAppium(MyTestExecutor.java:165)
	at com.appium.manager.ParallelThread.parallelExecution(ParallelThread.java:133)
	at com.appium.manager.ParallelThread.triggerTest(ParallelThread.java:66)
	at com.appium.manager.ParallelThread.runner(ParallelThread.java:62)
	at com.appium.tests.Runner.testRunner(Runner.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)

**Comment by saikrishna321** [comment]
@dkjha52 can you run the tests from commandline mvn clean -Dtest=Runner test and see if it goes well

**Comment by dkjha52** [comment]
Thanks. Its working fine using the command you mentioned. 
I am not using maven. I have explicitly added all the required jars and run the Runner. In that case I am getting issue. Please let me know how I can fix this issue without using maven.

**Comment by RatkoD** [comment]
It cannot run in other way rather than using maven. As I said before and Sai, if you use multiple devices, you need to run the tests from maven.
