### ISSUE TITLE
idevice_id still used for folder creation

### ISSUE THREAD

**Issue by RatkoD** [saikrishna321/AppiumTestDistribution#89]
It seems like idevice_id is still used for creating log folders plus device's UDIDs are stil concatenated when printing the detected device:
```
creating directory: Logs
No Device Connected
a55460712308b368e035ad4b61d065460f8966eb

a55460712308b368e035ad4b61d065460f8966ebc205d576285a38492cce0f8580c007f0abf37fac
```

3 log folders are created:
```
/usr/local/lib/node_modules/appium/build/lib
iOSWebKitProxyLauncher File already has access to execute
IOS a55460712308b368e035ad4b61d065460f8966eb Directory is created!
IOS c205d576285a38492cce0f8580c007f0abf37fac Directory is created!
IOS 68a967dd7f2f826dfca6061c5b6c76825acc6623 Directory is created!
```

And it says that 3 devices are detected:
```
***************************************************

Total Number of devices detected::**3**

***************************************************

```
And after that, the tests are run on the 2 actual devices:

```
starting running tests in threads
a55460712308b368e035ad4b61d065460f8966eb

a55460712308b368e035ad4b61d065460f8966ebc205d576285a38492cce0f8580c007f0abf37fac

Adding iOS devices
a55460712308b368e035ad4b61d065460f8966eb

a55460712308b368e035ad4b61d065460f8966ebc205d576285a38492cce0f8580c007f0abf37fac
```
And the tests are run only on the actually conected devices:
```
No Device Connected
{c205d576285a38492cce0f8580c007f0abf37fac=true, a55460712308b368e035ad4b61d065460f8966eb=true}
```

**Comment by saikrishna321** [comment]
@RatkoD did u try this from master ?

**Comment by RatkoD** [comment]
I've just tried it and it seems to work fine except for this part, where it sill prints concatenated UDIDs.

```
starting running tests in threads
a55460712308b368e035ad4b61d065460f8966eb

a55460712308b368e035ad4b61d065460f8966ebc205d576285a38492cce0f8580c007f0abf37fac

Adding iOS devices
a55460712308b368e035ad4b61d065460f8966eb

a55460712308b368e035ad4b61d065460f8966ebc205d576285a38492cce0f8580c007f0abf37fac

No Device Connected
{c205d576285a38492cce0f8580c007f0abf37fac=true, a55460712308b368e035ad4b61d065460f8966eb=true}
```

**Comment by saikrishna321** [comment]
i have merged your changes. can u try now.. guess that would have fixed it .

**Comment by saikrishna321** [comment]
@RatkoD ping ?

**Comment by RatkoD** [comment]
This is still an open issue, but now, tests wont start because of ghost devices and previously they were shown as failed on a ghost device. Now when my test starts i get
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.appium.tests.runners.RunnerQADemo
Configuring TestNG with: TestNG652Configurator
                            _  _        _ 
 _ __    __ _  _ __   __ _ | || |  ___ | |
| '_ \  / _` || '__| / _` || || | / _ \| |
| |_) || (_| || |   | (_| || || ||  __/| |
| .__/  \__,_||_|    \__,_||_||_| \___||_|
|_|                                       

creating directory: Logs
No Device Connected
a55460712308b368e035ad4b61d065460f8966eb

/usr/local/lib/node_modules/appium/build/lib
iOSWebKitProxyLauncher File already has access to execute
IOS a55460712308b368e035ad4b61d065460f8966eb Directory is created!
IOS 48e0ad307bb7bac9cb0a5a0eeb027d19ceac005d Directory is created!
***************************************************

Total Number of devices detected::2

***************************************************

starting running tests in threads
Adding iOS devices
No Device Connected
{a55460712308b368e035ad4b61d065460f8966eb=true}
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.292 sec <<< FAILURE! - in com.appium.tests.runners.RunnerQADemo
testApp(com.appium.tests.runners.RunnerQADemo)  Time elapsed: 3.831 sec  <<< FAILURE!
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.appium.executor.MyTestExecutor.constructXmlSuiteForParallel(MyTestExecutor.java:174)
	at com.appium.executor.MyTestExecutor.runMethodParallelAppium(MyTestExecutor.java:128)
	at com.appium.manager.ParallelThread.parallelExecution(ParallelThread.java:135)
	at com.appium.manager.ParallelThread.triggerTest(ParallelThread.java:60)
	at com.appium.manager.ParallelThread.runner(ParallelThread.java:52)
	at com.appium.tests.runners.RunnerQADemo.testApp(RunnerQADemo.java:15)


Results :

Failed tests: 
  RunnerQADemo.testApp:15 » IndexOutOfBounds Index: 1, Size: 1

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```
idevice is clearly showing two devices connected:
```
HRHeroQA $idevice_id -l
a55460712308b368e035ad4b61d065460f8966eb
48e0ad307bb7bac9cb0a5a0eeb027d19ceac005d
```
while system profiler is showing the actual connected device
```
HRHeroQA $system_profiler SPUSBDataType | sed -n -E -e '/(iPhone|iPad)/,/Serial/s/ Serial Number: (.+)/\1/p'
         a55460712308b368e035ad4b61d065460f8966eb
```

**Comment by RatkoD** [comment]
I think this is related to #159

**Comment by RatkoD** [comment]
I think I found a workaround, but still think that this should be fixed within the framework.
Disabling the mDNS seems to solves the issue with ghost devices which are actually connecting to the PC if they are on the same network.

```
sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist
sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.mDNSResponderHelper.plist
```

**Comment by RatkoD** [comment]
Hey @saikrishna321, I remember the fix, but please see the logs that I've attached.

**Comment by saikrishna321** [comment]
@RatkoD we missed in other place, i have fixed it now.

**Comment by RatkoD** [comment]
I'll try it in a few hours and let you know. BTW when do you plan a new release?

**Comment by saikrishna321** [comment]
> when do you plan a new release?

Once this PR is merged https://github.com/saikrishna321/AppiumTestDistribution/pull/157

**Comment by RatkoD** [comment]
@saikrishna321 where did you fixed it? Master?
