### ISSUE TITLE
Cannot run program "adb": error=2, No such file or directory Failed to initialise framework issue after set ANDROID_HOME in run config environment.

### ISSUE THREAD

**Issue by ssrikantasahoo** [saikrishna321/AppiumTestDistribution#98]
java.io.IOException: Cannot run program "adb": error=2, No such file or directory
Failed to initialize framework
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.appium.utils.CommandPrompt.runCommand(CommandPrompt.java:21)
	at com.appium.manager.AndroidDeviceConfiguration.startADB(AndroidDeviceConfiguration.java:21)
	at com.appium.manager.AndroidDeviceConfiguration.getDeviceSerial(AndroidDeviceConfiguration.java:89)
	at com.appium.manager.AppiumParallelTest.<clinit>(AppiumParallelTest.java:95)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:377)
	at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:290)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:125)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:190)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:130)
	at org.testng.TestRunner.initMethods(TestRunner.java:424)
	at org.testng.TestRunner.init(TestRunner.java:247)
	at org.testng.TestRunner.init(TestRunner.java:217)
	at org.testng.TestRunner.<init>(TestRunner.java:169)
	at org.testng.remote.support.RemoteTestNG6_9_10$1.newTestRunner(RemoteTestNG6_9_10.java:28)
	at org.testng.remote.support.RemoteTestNG6_9_10$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_9_10.java:61)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:594)
	at org.testng.SuiteRunner.init(SuiteRunner.java:168)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:117)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1319)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1306)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1160)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 33 more
[TestNG] Running:
  /private/var/folders/zs/bh3ckr411xl_8gncp60b0l5w0000gn/T/testng-eclipse-28874428/testng-customsuite.xml

Before Class called1
com.appium.webtest.LoginTest
No devices are free to run test or Failed to run test
Setting Android Desired Capabilities:
/Users/srikantakumarsahoo/Downloads/workspace/AppiumTestDistribution
Not taking ExtendReporting
FAILED CONFIGURATION: @BeforeMethod startApp(public void com.appium.webtest.LoginTest.loginTest() throws java.lang.InterruptedException)
java.lang.NullPointerException
	at com.appium.manager.AppiumParallelTest.setAuthorName(AppiumParallelTest.java:231)
	at com.appium.manager.AppiumParallelTest.startAppiumServerInParallel(AppiumParallelTest.java:213)
	at com.test.site.UserBaseTest.startApp(UserBaseTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:589)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)

SKIPPED CONFIGURATION: @AfterMethod killServer
SKIPPED CONFIGURATION: @AfterClass afterClass
SKIPPED: loginTest on [LoginTest passed=0 failed=0 skipped=0]

===============================================
    Default test
    Tests run: 1, Failures: 0, Skips: 1
    Configuration Failures: 1, Skips: 2
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 0, Skips: 1
Configuration Failures: 1, Skips: 2
===============================================

[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@13fee20c: 12 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@17550481: 35 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@1e67b872: 7 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@77b52d12: 6 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 5 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@6be46e8f: 3 ms

**Comment by aryak93** [comment]
Any progress on this. I'm also facing the same issue.

**Comment by saikrishna321** [comment]
@aryak93 are you running your test from eclipse?

**Comment by KumarNellore** [comment]
@aryak93 For this we have to set Android tool and tool path in path variable of Eclipse.

**Comment by saikrishna321** [comment]
Closing as inactive

**Comment by MuraliJallu** [comment]
Hi SaiKrishana how can i contact to you 
my mail id qa.murali90@gmail.com please message me

**Comment by saikrishna321** [comment]
@MuraliJallu pls join the slack channel https://join.slack.com/t/appiumtestparallel/shared_invite/MjIxMjIwMzMyMTAyLTE1MDE1NjY3NTgtMWMzMjM4YTI0ZA
